### ISSUE TITLE
making topbar responsive for ipad screens

### ISSUE THREAD

**Issue by Gjeev** [Gjeev/PaAC-website#30]
![image](https://github.com/Gjeev/PaAC-website/assets/97738003/2b5a5d44-69fe-4b90-85b4-ad4c5aa6de97)
add appropiate media queries

**Comment by A-4-Atom** [comment]
Hi, I'd like to work on it, can you assign it to me if it's possible.
thanks.

**Comment by Gjeev** [comment]
> Hi, I'd like to work on it, can you assign it to me if it's possible. thanks. @Gjeev

hi @A-4-Atom, i just saw your message and we fixed this bug recently but we appreciate it so please feel free to work on any of our other open issues! i can assign them to you.
